name: VyOS 1.4 sv fullconenat dae kernel Build and Release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:current
      env:
        TZ: Asia/Shanghai
      options: --privileged
      
    steps:

    - name: git clone vyos-kernel-build
      run: |
        set -eux
        
        git clone  -b dev-sv-dae-fullconenat https://github.com/debiansid/vyos-kernel-sv-fullconenat vyos-build

    - name: make deb
    #  working-directory: vyos-kernel-sv-fullconenat
      run: |
        set -eux
        pwd
        sudo apt-get --install-recommends install pahole dwarves
        cd vyos-build
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.8.tar.xz
        tar xf linux-6.1.8.tar.xz
        ln -s linux-6.1.8 linux
        ./build-kernel.sh
        rm *dev*.deb *dbg*.deb
    
    - name: make intel-qat deb
      run: |
        set -eux
        pwd
        cd vyos-build
        ./build-intel-qat.sh
         cp *.deb ../

    - name: ls
      run: |
        set -eux

        pwd
        ls -lah vyos-build

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          files: |
               vyos-build/linux*.deb
               vyos-build/vyos-*.deb
          draft: true
          prerelease: true
          
