name: VyOS 1.4 sv fullconenat dae kernel Build and Release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: git clone vyos-kernel-build
      run: |
        set -eux
        
        git clone  -b dev https://github.com/debiansid/vyos-kernel-sv-fullconenat

    - name: make deb
      working-directory: vyos-kernel-sv-fullconenat
      run: |
        ./build-kerel.sh


    - name: ls
      run: |
        set -eux

        pwd
        ls -lah
        ls -lah linux

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          files: vyos-kernel-sv-fullconenat/linux/*.deb
          draft: true
          prerelease: true
          
